= icon:cogs[] Brine Specifications
Matt Whipple <http://github.com/mwhipple[@mwhipple]>
:description: Specifications for Brine
:keywords: Brine, Cucumber, RESt, DSL

== Request Construction
gherkin::../../features/request_construction/basic.feature[spec.erb]
gherkin::../../features/request_construction/body.feature[spec.erb]
gherkin::../../features/request_construction/params.feature[spec.erb]
gherkin::../../features/request_construction/headers.feature[spec.erb]
gherkin::../../features/request_construction/clearing.feature[spec.erb]

== Resource Cleanup
gherkin::../../features/resource_cleanup/cleanup.feature[spec.erb]

== Selection
gherkin::../../features/selectors/any.feature[spec.erb]
gherkin::../../features/selectors/all.feature[spec.erb]

== Assertion
gherkin::../../features/assertions/is_equal_to.feature[spec.erb]
gherkin::../../features/assertions/is_matching.feature[spec.erb]
gherkin::../../features/assertions/is_including.feature[spec.erb]
gherkin::../../features/assertions/is_a_valid.feature[spec.erb]